from __future__ import annotations
from datetime import datetime, timedelta, timezone
import json
import httpx
import pandas as pd
from sqlalchemy import text
from tenacity import retry, stop_after_attempt, wait_exponential

from .config import settings
from .database import engine
from .discord import send_crypto_alert
from .models import ResearchResult, TradeIdea
from .scanner import rank_technicals
from .scoring import make_ideas


class AlpacaCryptoData:
    trading_base = "https://paper-api.alpaca.markets"
    data_base = "https://data.alpaca.markets"

    def __init__(self):
        self.headers = {
            "APCA-API-KEY-ID": settings.alpaca_api_key,
            "APCA-API-SECRET-KEY": settings.alpaca_secret_key,
        }
        self.client = httpx.Client(timeout=30.0, headers=self.headers)

    @retry(stop=stop_after_attempt(3), wait=wait_exponential(min=1, max=8))
    def universe(self) -> list[str]:
        r = self.client.get(
            f"{self.trading_base}/v2/assets",
            params={"status": "active", "asset_class": "crypto"},
        )
        r.raise_for_status()
        assets = r.json()
        symbols = []
        for a in assets:
            symbol = str(a.get("symbol") or "")
            if a.get("tradable") and "/" in symbol:
                symbols.append(symbol)
        return sorted(set(symbols))

    @retry(stop=stop_after_attempt(3), wait=wait_exponential(min=1, max=8))
    def bars_5m(self, symbols: list[str], lookback_hours: int = 48) -> dict[str, pd.DataFrame]:
        if not symbols:
            return {}
        start = (datetime.now(timezone.utc) - timedelta(hours=lookback_hours)).isoformat()
        out: dict[str, pd.DataFrame] = {}
        for i in range(0, len(symbols), 50):
            chunk = symbols[i:i+50]
            r = self.client.get(
                f"{self.data_base}/v1beta3/crypto/us/bars",
                params={
                    "symbols": ",".join(chunk),
                    "timeframe": "5Min",
                    "start": start,
                    "limit": 10000,
                    "sort": "asc",
                },
            )
            r.raise_for_status()
            payload = r.json().get("bars", {})
            for symbol, rows in payload.items():
                if not rows:
                    continue
                df = pd.DataFrame(rows).rename(columns={
                    "t": "timestamp", "o": "open", "h": "high", "l": "low",
                    "c": "close", "v": "volume",
                })
                df["timestamp"] = pd.to_datetime(df["timestamp"], utc=True)
                out[symbol] = df[["timestamp", "open", "high", "low", "close", "volume"]]
        return out


def _init_crypto_table():
    with engine.begin() as c:
        c.execute(text("""
        CREATE TABLE IF NOT EXISTS crypto_trade_ideas (
          id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
          fingerprint VARCHAR(255) UNIQUE NOT NULL,
          symbol VARCHAR(32) NOT NULL,
          created_at TIMESTAMP NOT NULL,
          score DOUBLE PRECISION NOT NULL,
          status VARCHAR(32) NOT NULL,
          payload TEXT NOT NULL,
          alerted BOOLEAN NOT NULL DEFAULT FALSE
        )
        """ if engine.dialect.name == "postgresql" else """
        CREATE TABLE IF NOT EXISTS crypto_trade_ideas (
          id INTEGER PRIMARY KEY AUTOINCREMENT,
          fingerprint TEXT UNIQUE NOT NULL,
          symbol TEXT NOT NULL,
          created_at TEXT NOT NULL,
          score REAL NOT NULL,
          status TEXT NOT NULL,
          payload TEXT NOT NULL,
          alerted INTEGER NOT NULL DEFAULT 0
        )"""))


def _fingerprint(idea: TradeIdea) -> str:
    return (
        f"crypto:{idea.symbol}:{idea.direction}:{idea.setup}:"
        f"{idea.entry_low:.4f}:{idea.entry_high:.4f}:{int(idea.score // 3)}"
    )


def _save_new(idea: TradeIdea) -> bool:
    fp = _fingerprint(idea)
    with engine.begin() as c:
        row = c.execute(
            text("SELECT alerted FROM crypto_trade_ideas WHERE fingerprint=:fp"),
            {"fp": fp},
        ).fetchone()
        if row:
            return False
        c.execute(
            text("""
            INSERT INTO crypto_trade_ideas(fingerprint,symbol,created_at,score,status,payload,alerted)
            VALUES(:fp,:s,:t,:sc,:st,:p,:a)
            """),
            {
                "fp": fp,
                "s": idea.symbol,
                "t": datetime.now(timezone.utc),
                "sc": idea.score,
                "st": idea.status,
                "p": json.dumps(idea.to_dict()),
                "a": False,
            },
        )
    return True


def crypto_diagnostics() -> dict:
    md = AlpacaCryptoData()
    symbols = md.universe()
    bars = md.bars_5m(symbols)
    technicals = rank_technicals(bars, settings.crypto_technical_limit)
    research = ResearchResult("CRYPTO", "Hold", 55.0, "Zero-cost deterministic crypto mode")
    raw_ideas: list[TradeIdea] = []
    for t in technicals:
        for idea in make_ideas(t, research, market_score=65):
            idea.shares = 0
            if idea.status != "INVALID":
                raw_ideas.append(idea)
    raw_ideas.sort(key=lambda x: x.score, reverse=True)
    return {
        "pairs": len(symbols),
        "pairs_with_bars": len(bars),
        "technicals": len(technicals),
        "threshold": settings.crypto_min_entry_score,
        "top_ideas": raw_ideas[:10],
    }


def run_crypto_once() -> list[TradeIdea]:
    _init_crypto_table()
    diag = crypto_diagnostics()
    results: list[TradeIdea] = []
    for idea in diag["top_ideas"]:
        if idea.score < settings.crypto_min_entry_score:
            continue
        if _save_new(idea):
            send_crypto_alert(idea)
        results.append(idea)
    return sorted(results, key=lambda x: x.score, reverse=True)
