from __future__ import annotations
from datetime import datetime, timezone
import json
from sqlalchemy import create_engine, text
from .config import settings
from .models import TradeIdea


def _url():
    url = settings.database_url
    if url.startswith("postgres://"):
        url = "postgresql+psycopg://" + url[len("postgres://"):]
    elif url.startswith("postgresql://"):
        url = "postgresql+psycopg://" + url[len("postgresql://"):]
    return url

engine = create_engine(_url(), pool_pre_ping=True)


def init_db():
    with engine.begin() as c:
        c.execute(text("""
        CREATE TABLE IF NOT EXISTS trade_ideas (
          id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
          fingerprint VARCHAR(255) UNIQUE NOT NULL,
          symbol VARCHAR(20) NOT NULL,
          created_at TIMESTAMP NOT NULL,
          score DOUBLE PRECISION NOT NULL,
          status VARCHAR(32) NOT NULL,
          payload TEXT NOT NULL,
          alerted BOOLEAN NOT NULL DEFAULT FALSE,
          outcome VARCHAR(32),
          outcome_at TIMESTAMP
        )
        """ if engine.dialect.name == "postgresql" else """
        CREATE TABLE IF NOT EXISTS trade_ideas (
          id INTEGER PRIMARY KEY AUTOINCREMENT,
          fingerprint TEXT UNIQUE NOT NULL,
          symbol TEXT NOT NULL,
          created_at TEXT NOT NULL,
          score REAL NOT NULL,
          status TEXT NOT NULL,
          payload TEXT NOT NULL,
          alerted INTEGER NOT NULL DEFAULT 0,
          outcome TEXT,
          outcome_at TEXT
        )"""))


def fingerprint(idea: TradeIdea) -> str:
    return f"{idea.symbol}:{idea.direction}:{idea.setup}:{idea.entry_low:.2f}:{idea.entry_high:.2f}:{int(idea.score//3)}"


def save_idea(idea: TradeIdea) -> tuple[str, bool]:
    fp = fingerprint(idea)
    payload = json.dumps(idea.to_dict())
    created = datetime.now(timezone.utc)
    with engine.begin() as c:
        row = c.execute(text("SELECT alerted FROM trade_ideas WHERE fingerprint=:fp"), {"fp": fp}).fetchone()
        if row:
            return fp, False
        c.execute(text("INSERT INTO trade_ideas(fingerprint,symbol,created_at,score,status,payload,alerted) VALUES(:fp,:s,:t,:sc,:st,:p,:a)"),
                  {"fp":fp,"s":idea.symbol,"t":created,"sc":idea.score,"st":idea.status,"p":payload,"a":False})
    return fp, True


def mark_alerted(fp: str):
    with engine.begin() as c:
        c.execute(text("UPDATE trade_ideas SET alerted=:a WHERE fingerprint=:fp"), {"a":True,"fp":fp})


def unresolved_ideas(limit: int = 200):
    with engine.begin() as c:
        rows = c.execute(text("SELECT fingerprint,created_at,payload FROM trade_ideas WHERE outcome IS NULL ORDER BY created_at DESC LIMIT :n"), {"n": limit}).fetchall()
    return rows


def record_outcome(fp: str, outcome: str):
    with engine.begin() as c:
        c.execute(text("UPDATE trade_ideas SET outcome=:o,outcome_at=:t WHERE fingerprint=:fp AND outcome IS NULL"),
                  {"o": outcome, "t": datetime.now(timezone.utc), "fp": fp})
